version: "3"
volumes:
  redis:
  postgres:

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: godwd_development
    # environment:
    #   - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/1"
      POSTGRES_PASSWORD: postgres
    ports:
      - "3001:3001"
    depends_on:
      - "db"
      - "redis"
    env_file:
      - ".env"

  redis:
    image: redis
    command: redis-server
    environment:
      REDIS_URL: redis://redis:6379/1
    volumes:
      - redis:/data

  sidekiq:
    build: .
    command: "bundle exec sidekiq -C config/sidekiq.yml"
    volumes:
      - .:/api
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/1"
    depends_on:
      - "redis"
      - "db"
    env_file:
      - ".env"
