version: "3"
volumes:
  redis:
  postgres:

services:
  postgres:
    image: postgres
    # environment:
    #   POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ".env"

  web:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/api
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/12"
    ports:
      - "3001:3001"
    depends_on:
      - "postgres"
      - "redis"
    env_file:
      - ".env"

  redis:
    image: redis
    command: redis-server
    environment:
      REDIS_URL: redis://redis:6379/12
    volumes:
      - redis:/data

  sidekiq:
    build: .
    command: "bundle exec sidekiq -C config/sidekiq.yml"
    volumes:
      - .:/api
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/12"
    depends_on:
      - "redis"
      - "postgres"
    env_file:
      - ".env"
