version: "3.8"

services:
  redis:
    image: redis
    command: redis-server
    environment:
      REDIS_URL: redis://redis:6379/1
    volumes:
      - ./tmp/redis:/data

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: godwd_development
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  sidekiq:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile-rails
    # command: "bundle exec sidekiq -C config/sidekiq.yml"
    # volumes:
    #   - .:/myapp
    environment:
      - RAILS_ENV=$RAILS_ENV
      - REDIS_URL=redis://redis:6379/1
      - ENABLE_BOOTSNAP=true
    depends_on:
      - redis
      - db
    env_file: .env

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile-rails
      args:
        RAILS_ENV: $RAILS_ENV
    depends_on:
      - db
      - redis
    # command: "bundle exec puma -C config/puma.rb"
    environment:
      - RAILS_ENV=$RAILS_ENV
      - REDIS_URL=redis://redis:6379/1
      - POSTGRES_PASSWORD=postgres
      - ENABLE_BOOTSNAP=true
    ports:
      - "3001:3001"
    env_file: .env

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile-nginx
      args:
        RAILS_ENV: $RAILS_ENV
    ports:
      - 8080:80
    depends_on:
      - app
