branch-defaults:
  aws:
    environment: null
    group_suffix: null
global:
  application_name: godwd
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Puma with Ruby 2.6 running on 64bit Amazon Linux
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
