default: &default
  adapter: postgresql
  encoding: unicode
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POsTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

  # Rails default, used by Foreman
  host: localhost

  # !!! for Docker  do ...!!!
  # host: db

development:
  <<: *default
  database: godwd_development
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: godwd_production
  # url: <%= ENV['DATABASE_URL'] %>
  # postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...]
  # url: "postgresql://postgres:postgres@localhost:5432/godwd_development"
  #
  #### Heroku
  # url: <%= ENV['DATABASE_URL'] %>
  #### CleverCloud
  # url: <%= ENV['POSTGRESQL_ADDON_URI'] %>
