default: &default
  adapter: postgresql
  encoding: unicode
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  # host: localhost # Rails default, used by Foreman
  # host: db # !!! for Docker !!!

development:
  <<: *default
  database: godwd_development

#
production:
  <<: *default
  database: godwd_production

  # Heroku
  url: <%= ENV['DATABASE_URL'] %>
  # CleverCloud
  # url: <%= ENV['POSTGRESQL_ADDON_URI'] %>
  #   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
