default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  database: <%= ENV.fetch('POSTGRES_DB') %>

  # Rails default, used by Foreman
  # host: localhost
  # !!! for Docker  do ...!!!
  # host: db

development:
  <<: *default

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> # Heroku

  # postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...]
  # url: "postgresql://postgres:postgres@localhost:5432/godwd_development"
  #
  #### CleverCloud
  # url: <%= ENV['POSTGRESQL_ADDON_URI'] %>
