:concurrency: 5
:timeout: 8 # heroku
:verbose: true
:max_retries: 1
:queues: # Queue priority: https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - default
  - mailers
production:
  :logfile: ./log/sidekiq.log
