:concurrency: 3
:timeout: 8 # heroku
:verbose: true
:max_retries: 1
:queues: # Queue priority: https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - default
  - mailers
production:
  :logfile: ./log/sidekiq.log
# we defined a queue 'mailers' so this file is need
# cf https://github.com/mperham/sidekiq/wiki/Advanced-Options
# the concurrency value is calculated as per:
# https://manuelvanrijn.nl/sidekiq-heroku-redis-calc/
